language: node_js
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - secure: 0r/8Xn6dJdaB4MmvYjlWHRTWpYmBePQq2xD78zwzDuvpncsF+pxK5mPbwHaRIHrvazcPQ/Y2v8fhwM2gTz/vo8MSchsggqCqSCJsUVPNspLzhmvnUxfJmu9R7cLF1FdAkSirzLmdbbpNY7FXpR8Rty1eXZ+btjqEwE2Zoi+8QmMBANDLOFdP3uuOUmPzi3m378Xpnv/JGBkatCDZADqU1GdkS/tWm6GT+BsqFbEH4LgYHr8JFwtswGWkMQ3Bq9ZMOAC8M+ma9OBvel13R1oLiFxMyOwIKFi7jZwFnVIL0t06mcIaPzkUZUdvjlNUtxUJ3MwbXiO39hhE5lh8fNaraCs2971aBaiL28N1FdHrvTO588gdrattTMmJ8whfk/3JHqqcS9BKv6zpX3k7xo+Dxbzt/3zvdABYkyNs9uokrOHmCsBSruSL7qt9R0bZvNNqF3KKgQKlzZvYz7d1Ra33vELJiEAQ7cjB5w6o/7JIezfnfsCQbuwaRJq82skpuYz39U2WJePZkkix7Gla9uAUP781pNHm3fCrTB+QjNKfX66OdL0jyiNoqQR3fS226BKOf76vWk/c2Uy55Ue3X3Lrv+2QB7lEWMrZyhFkvaRR1S9wAa59LjlwfvkedJSt3t22H9pinXsaBZEHpxDcIWSu7KC1IcLOVCTPpGbAgBo/FLc=
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- ./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "xN9Ru9Fed3RZDhSIzbLbHnFWby3YvmiTvAcNAyB2kXTPm3Ps/oDDZehidVztHq8JfrhrL/5AgvWlUOLueDNGZY0+V3Ll0z0ihZ77DvWjDVq98iNN+4zxm0q9sReh71XTYrJyMdzgMNqbItVzy2fBWxvtIAMXALfRTGAIzNUMZ+bqcRDBSPDJ8DZD4/3YvOvOJRLUasNHrZ8zIORG1XWaZx8ZBKTiLy65frn7q6jz2ZiYktjlkLrBpO44itG3awHy75PKuO4kUHjGNfWqBz1FgbGGJpivkk43FWvFTnSLbqNSK5nndLyqYcWUze98k8S01lVMBw+aGkLn4aOi876hX575ZNdwCQJOADbWeVcOQ3w5WjeOLnVGfz9TXhxOECPD4y3EHxwVzN1n7xm3OtO3RBgO+tOPTXEIxNZCQ3tFtbJ4o0opEDH+nn1e8jlMD2aEWFieiMoX71IOkoRWWeGhhgR/Y6RrI7iAeW5Qs96qlEHlmNU0QrLnwZ1qObAU/ElxV1WT5tFcdnVMyLKcwqkBybQejN1GNhCBSJlcul0+9Em8dikO5bVP/fl/lsnGJRY5IDJUdSBrDMTMLD2tvTmhE8JtvgzUEG5jcbJMI0nNVbHzrSV37qH06Hq9guQW/xo1vF4a36qRRaGNup6tClFSKqLFYw1jeOS6CqCgnAjBI7s="
  bucket: endo-manager.octoblu.com
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  local-dir: dist
  on:
    tags: true
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "xN9Ru9Fed3RZDhSIzbLbHnFWby3YvmiTvAcNAyB2kXTPm3Ps/oDDZehidVztHq8JfrhrL/5AgvWlUOLueDNGZY0+V3Ll0z0ihZ77DvWjDVq98iNN+4zxm0q9sReh71XTYrJyMdzgMNqbItVzy2fBWxvtIAMXALfRTGAIzNUMZ+bqcRDBSPDJ8DZD4/3YvOvOJRLUasNHrZ8zIORG1XWaZx8ZBKTiLy65frn7q6jz2ZiYktjlkLrBpO44itG3awHy75PKuO4kUHjGNfWqBz1FgbGGJpivkk43FWvFTnSLbqNSK5nndLyqYcWUze98k8S01lVMBw+aGkLn4aOi876hX575ZNdwCQJOADbWeVcOQ3w5WjeOLnVGfz9TXhxOECPD4y3EHxwVzN1n7xm3OtO3RBgO+tOPTXEIxNZCQ3tFtbJ4o0opEDH+nn1e8jlMD2aEWFieiMoX71IOkoRWWeGhhgR/Y6RrI7iAeW5Qs96qlEHlmNU0QrLnwZ1qObAU/ElxV1WT5tFcdnVMyLKcwqkBybQejN1GNhCBSJlcul0+9Em8dikO5bVP/fl/lsnGJRY5IDJUdSBrDMTMLD2tvTmhE8JtvgzUEG5jcbJMI0nNVbHzrSV37qH06Hq9guQW/xo1vF4a36qRRaGNup6tClFSKqLFYw1jeOS6CqCgnAjBI7s="
  bucket: endo-manager-dev.octoblu.com
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  local-dir: dist
  on:
    tags: true
